// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nimnvoialnlozikfifqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pbW52b2lhbG5sb3ppa2ZpZnF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzUwNTMsImV4cCI6MjA2NTkxMTA1M30.HKOlujcqVUZErsd74y1EQ88_xuZacPj1swSC42Lm-Cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);